### ISSUE TITLE
Explicit length check

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-xo#12]
I want to enforce doing `if (arr.length > 0) {` over just `if (arr.length) {`. Same with `!arr.length`. I think we can safely assume `.length` is a number. I generally favor explicitness. Should be autofixable.

**Comment by jfmengels** [comment]
Should also handle `if (!arr.length) {}` --> `if (arr.length === 0) {}`

**Comment by jamestalmage** [comment]
We could also allow `if(Boolean(something.length))` for situations where `.length` was not a number.

I am not 100% sure on autofixing it though. It's definitely doable, but adding `> 0` potentially changes behavior. Not sure that we should apply autofixes unless we can guarantee it has no impact on behavior.

>  I think we can safely assume .length is a number.

*almost* always, yes. But I could definitely see somebody doing something like this:

```js
var line = new Line();
line.length = {
  feet: 6
  inches: 3
};

// later
if (!line.length) {
  throw new Error('you must set the line length');
}
```

I admit, it's a pretty remote possibility. But I think there's some danger to auto-fixing this type of thing. For starters - if people rely on the autofix, they don't learn to do it the right way. For missing semicolons / whitespace nits, who cares if they are a little sloppy - just fix it (it's often not their fault anyways - my IDE occasionally "helps" me make whitespace errors). For this type of stuff it might be better to just make them do it, so they develop good habits.

Anyways, that's my 2 cents. I'm not strongly against it. Just playing devils advocate.

**Comment by jfmengels** [comment]
I agree with @jamestalmage about the autofixing part, especially since this would change the form of the AST. Current ESLint recommendations for autofixing is limited to fixing stuff like whitespace. I prefer waiting on the rework of the autofixing that they are working on.

We should only lint when the access to the property `length` is
- at the root of an if condition `if (a.length) {}`
- inside a logical operation inside an if condition `if (a && a.length) {}`
- deeply nested inside a logical operation inside an if condition `if (a && (b && b.length)) {}`

We should not handle it when it's being passed as an argument `if (a && foo(b.length)) {}`
or used outside of an if condition `const a = b.length`.

**Comment by sindresorhus** [comment]
> Current ESLint recommendations for autofixing is limited to fixing stuff like whitespace.

They've actually backpedaled on that: https://mobile.twitter.com/geteslint/status/723909416957829122

> I prefer waiting on the rework of the autofixing that they are working on.

They've said that will take a lot longer and in the meantime they're going to make it slower but more correct by trying to apply as many fixes as possible.

-

That being said, I agree with skipping on auto-fixing this rule.

**Comment by jfmengels** [comment]
Ah, I thought that was still in the works. Okay, thanks.

**Comment by jamestalmage** [comment]
> They've actually backpedaled on that

Yeah, but the implementation is still a bit weird. You can't modify the AST directly, instead you replace nodes with straight text. Note the lack of `replace(someNode, someOtherNode)` type of function [here](https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-rules-new.md#applying-fixes).

`insertTextAfter(node, ' > 0')` would almost work for this rule, except for a few corner cases:

```js
if(!array.length) ...
// => 
if(!array.length > 0) ... // not what you intended I'm sure
```

You could try wrapping the expression in a parens, but that's becomes pretty involved.

Once we are able to replace nodes with other nodes everything gets easier.

I'm guessing it's going to be a while waiting for autofix to do exactly what we want. I think it will probably be [CST](https://github.com/cst/cst) based. That's what JSCS was using before the merge I believe, and it probably offered better auto-fixing.

**Comment by sindresorhus** [comment]
Yup, [CST](https://github.com/cst/cst) is the only real solution.

**Comment by gajus** [comment]
Has anyone found this useful in practice?

Whats the practical advantage of:

```js
if (string.length) {}
if (array.length) {}
if (!array.length) {}
```

over

```js
if (string.length > 0) {}
if (array.length > 0) {}
if (array.length !== 0) {}
if (array.length === 0) {}
```

?

After adding this rule, I've noticed more inconsistency in the code as a result of the addition. Specifically, all the code that previously was `array.length` now has become either `array.length > 1`  or `array.length !== 0`.

**Comment by jamestalmage** [comment]
Perhaps we should enforce one or the other `> 0` or `!== 0`

**Comment by gajus** [comment]
> Perhaps we should enforce one or the other > 0 or !== 0

But whats the reason to have this rule in the first place?

i.e. whats wrong with `string.length` and `!string.length`?

I see how this rule would make sense in the context of a strictly typed language, e.g. `string.length !== 0` would throw an error if `.length` is undefined (actually... it wouldn't even in this case; anyway).

But in JavaScript context, there will be no difference between `!names.length` and `names.length > 0` regardless of whether `length` value is `1` or `a` (string).

**Comment by sindresorhus** [comment]
@gajus More readable and strict code.

The inconsistency will be fixed with: https://github.com/sindresorhus/eslint-plugin-unicorn/issues/56
