### ISSUE TITLE
No template literals in normal strings

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-xo#15]
https://github.com/eslint/eslint/issues/5850
Do we want to create a rule for this here?
I don't think it happens often but can be useful, and we might as well put it here as we have/want plenty of different type of rules.

**Comment by sindresorhus** [comment]
Yeah. Doesn't have to happen often to be useful.

Might want to wait on this though (from linked issue):

> I'll leave this open for a bit to see if anyone on the team wants to disagree.

**Comment by ljharb** [comment]
It's now closed, sadly. I'd love to be able to use this rule.

**Comment by sindresorhus** [comment]
Alright. Let's do it then.

**Comment by ljharb** [comment]
@sindresorhus it'd be awesome if it could be done standalone, and made a dep of this one, so i can use it in other packages without having to bring in this entire package :-)

**Comment by jfmengels** [comment]
You wouldn't get much less by having a standalone module (there a not a lot of dependencies... yet), and maybe you'll want all the awesome rules that it has and will have? :D

More seriously, to me, it's a bit of a pain to create a new project for it. I agree that you might not want all the rest, but maintaining-wise, it's simpler to have it in a project that is actively maintained by several people, not in a corner somewhere. I proposed to add it here because it's kind of a specific rule, with no existing plugin (afaik) it could get included in, and because this is a collection of various rules.

Then again, if we write this rule, you're free to copy it in a new repo and use it as you see fit.

**Comment by ljharb** [comment]
I use `eslint-find-rules --unused` to ensure that all rules available are defined, so if I bring in a plugin with N rules, i have to add N lines to my eslint config.

If the authors don't mind, then once written, I'd be happy to spend the few minutes required to create a new project, and would be happy to copy the code and share ownership/maintainership of it, especially if this module could pull it in as a dep.

**Comment by jamestalmage** [comment]
> More seriously, to me, it's a bit of a pain to create a new project for it.

Maybe we should build this project as a monorepo? Split each rule into its own package? It would be interesting to explore what AVA and XO could do to enable monorepo development:

- shared config
- easily test/lint all submodules/packages
- easily test/lint an individual submodule/package

**Comment by jfmengels** [comment]
> Maybe we should build this project as a monorepo

Can be interesting.

> explore what AVA and XO could do to enable monorepo development

Does AVA already do something monorepo-like, or are you suggesting it could start doing something in that vein?

**Comment by sindresorhus** [comment]
I'm really not a big fan of monorepos. It would also add a lot of overhead. I think the rules we have now makes sense in one package. We currently have a nice setup with tests, docs and code coverage. I don't really see the problem depending on this plugin, even if you only want one rule. We currently only have 4 tiny dependencies. Dependencies matters less in a dev environment.

> I use eslint-find-rules --unused to ensure that all rules available are defined, so if I bring in a plugin with N rules, i have to add N lines to my eslint config.

I would rather fix that module. It should have an ignore option.

**Comment by jfmengels** [comment]
Closing as it's being integrated in ESLint core rules https://github.com/eslint/eslint/pull/6767
