### ISSUE TITLE
Exceptions to `no-process-exit` rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/eslint-plugin-xo#32]
Sometimes it does make sense to use `process.exit()`:

```js
process.on('uncaughtException', err => {
	console.error('Exception:', err);
	process.exit(1);
});
```

```js
process.on('SIGINT', () => {
	console.log('Got SIGINT');
	process.exit(1);
});
```

I think we should make an exception when it's inside a `process` event listener.

**Comment by jfmengels** [comment]
That would allow you to put a `process.exit` call anywhere in your program.

I'd say
- you could put all these event listener in your cli file (the one with a hashbang)
- that would be a valid case for adding a `eslint disable` comment, as it warrants IMO at least a comment to show that this file can cause your program to exit.

**Comment by sindresorhus** [comment]
> That would allow you to put a process.exit call anywhere in your program.

No, only directly inside the `process` event listener.

-

I think these cases should be allowed as they're valid use-cases for `process.exit()`. I don't see why we can't be user-friendly here.

**Comment by sindresorhus** [comment]
> you could put all these event listener in your cli file (the one with a hashbang)

It's not just CLI apps that use `uncaughtException`. Servers, worker, and apps too. Real world usage: https://github.com/sindresorhus/electron-config/blob/4ead4f9699bee920a7e60ea7e5a452eec3c24cda/fixture.js#L7

**Comment by jfmengels** [comment]
:+1: 

Do we want to handle only this:
```js
process.on('SIGINT', () => {
    process.exit(1);
});
```
or go the extra mile and handle this:
```js
function exit() {
  process.exit(1);
}

process.on('uncaughtException', exit);
process.on('SIGINT', exit);
```

**Comment by sindresorhus** [comment]
Only the former.
