### ISSUE TITLE
`filename-case` complains about `s3fs.js`

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/eslint-plugin-xo#37]
Is it my wrong or is the plugin a little bit too strict in this case? I don't really want to rename it to `s-3-fs.js` because it looks really weird.

![screen shot 2016-06-14 at 14 17 00](https://cloud.githubusercontent.com/assets/1913805/16042381/af0c58a6-323a-11e6-962f-7d3b4d55333b.png)

**Comment by sindresorhus** [comment]
I think this was fixed in https://github.com/sindresorhus/eslint-plugin-xo/commit/198bb6a7deb946ab17d0b223e3dbfe3ef05779a2.

**Comment by SamVerschueren** [comment]
Will check it again later today. Thought I reinstalled XO but will try it again.

**Comment by sindresorhus** [comment]
@SamVerschueren It's not yet part of XO. I'm planning a new XO release soon.

**Comment by SamVerschueren** [comment]
Oh ok. You can close it if you like or keep it open for tracking.

**Comment by jfmengels** [comment]
I confirm that this should be fixed in 198bb6a. I'll close, but do re-open it if you find it to still be broken.
