### ISSUE TITLE
FileName is not in kebab case for gulpFile

### ISSUE THREAD

**Issue by tarungarg546** [sindresorhus/eslint-plugin-xo#38]
Hey there,

I am using gulp-xo a gulp plugin for 'xo' which is essentially using eslint-plugin-xo and i am seeing following error when i tried to use gulp-xo.

This error is related to rule checking for kebab case and it seems like you guys are doing it and its from your end that this mistake is still there.

![capture](https://cloud.githubusercontent.com/assets/10435209/16128430/578eb23c-341e-11e6-8337-6b290c577da3.PNG)

Tell me what needs to be fixed so that i can go ahead with my work and FYI i cant rename gulpFile to gulp-file :tanabata_tree:

**Comment by sindresorhus** [comment]
Rename your `gulpFile.js` to `gulpfile.js`.
