### ISSUE TITLE
use strict or module syntax 

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/eslint-plugin-xo#41]
https://github.com/bmeck/UnambiguousJavaScriptGrammar/blob/master/README.md

The file should either contain `use strict` stanza at the top. Or have an `export` statement.

See the link above.

`export { }` declares module mode (and means export nothing).

Once that proposal is accepted - that brings other interesting opportunities for `xo` (i.e. turn on esnext in modules)

**Comment by jfmengels** [comment]
I saw some disapproving comments from a TC39 member, so not sure this will pass. But :+1: with the idea. Let's wait until this gets approved, or do you think this is worth it anyway already?
https://twitter.com/domenic/status/743979089770463232
https://twitter.com/domenic/status/743981189732642816

**Comment by jamestalmage** [comment]
No need to rush into anything. Just wanted to get the idea in the issue tracker.

**Comment by jfmengels** [comment]
Actually, it's probably a better fit here https://github.com/benmosher/eslint-plugin-import/issues/384

**Comment by jamestalmage** [comment]
Hmm. Enforcing `use strict` as the alternative seems out of scope for that library, but whatever. As long as we find a way to reliably tell me I've forgotten `use strict` - I'm good

**Comment by jdalton** [comment]
ESLint already has `{parserOptions:{sourceType:"module"}}` which [will warn](https://github.com/nre/eslint/blob/97ac91c97de93549a6c2f619efabe43d56b8183e/lib/rules/strict.js#L27) if using "use strict" in ES modules. The UnambiguousJavaScriptGrammar would be used as an enhancement to auto detect if a file has at least an `import` or `export` declaration.

**Comment by sindresorhus** [comment]
@jdalton That didn't work at least the last time I tried: https://github.com/sindresorhus/eslint-config-xo/issues/7#issuecomment-207536236

**Comment by jdalton** [comment]
I followed the link but not sure which case did `sourceType:"module"` not work for?

**Comment by jdalton** [comment]
They now also have `impliedStrict` as a [parser option](http://eslint.org/docs/user-guide/configuring#specifying-parser-options).

**Comment by sindresorhus** [comment]
@jdalton Nvm, I misread your comment.

**Comment by jamestalmage** [comment]
Based on [this comment](https://github.com/benmosher/eslint-plugin-import/issues/384#issuecomment-227003041)

>> How would we avoid reporting situations where the user intends it to be a script, not a module?

> You wouldn't. This rule would be combo'ed with parserOptions:{sourceType:"module"} and warn if a file doesn't have at least an import or export declaration.

I think there's room for this rule here. XO is a zero/minimal config linter that supports both module and script syntax. This rule would not require any configuration and enforce best practices in both script and module modes.

We have previously discussed adding a `enforce-use-strict` rule, but couldn't because of the ambiguity of modules that don't `import` or `export`. With the introduction of [UnambiguousJavaScriptGrammar](https://github.com/bmeck/UnambiguousJavaScriptGrammar/), we have now got a way to enforce best practices and maintain zero config.

**Comment by jdalton** [comment]
> With the introduction of UnambiguousJavaScriptGrammar, we have now got a way to enforce best practices and maintain zero config.

If you think this is something to we can add to [external-impact](https://github.com/bmeck/UnambiguousJavaScriptGrammar/#external-impact) section a PR for that would be great!

**Comment by benmosher** [comment]
@jamestalmage @jfmengels I think you're both right. I think a `"use strict"` rule makes sense here, and I think a `This module is at risk of parsing as a script` rule makes sense in the `import` plugin.

**Comment by jfmengels** [comment]
I'm closing as it's being implemented in `eslint-plugin-import`.
