### ISSUE TITLE
Publish 1.0.0?

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-xo#46]
Shall we publish v1.0.0?
I noticed `explicit-length-check` was added a month and a half ago, but still not published. (I tried adding it to one of my projects, that's how I noticed)
There are some breaking changes, so it's a good opportunity to bump the major version.
Or do you want to wait until #43 is done?

**Comment by sindresorhus** [comment]
👍 Good idea, but should wait for #43 at least before doing a 1.0.0.

**Comment by jfmengels** [comment]
Sounds good, putting it on my todo list.

**Comment by sindresorhus** [comment]
Done

**Comment by jfmengels** [comment]
Cool, thanks!
