### ISSUE TITLE
`filename-case` rule

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-xo#5]
# Enforce a case style for file names

Enforces all linted files to have their names in a certain case style.

- `camelCase`: `fooBar.js` (default)
- `snakeCase`: `foo_bar.js`
- `kebabCase`: `foo-bar.js`

## Options

You can set the option in configuration like this:

```js
"stuff/filename-case": ["error", {"case": "camelCase"}]
```

I have just written it, thinking I would put it in a new random stuff plugin, but if you guys are interested in putting this in XO, I don't mind adding it here (I'm starting to have way too many plugins in my dev folder anyway...).

I'm thinking of adding an option to check the folder names up to the package.json too.

What do you think?

**Comment by sindresorhus** [comment]
Looks useful. Happy to have it added here :)

**Comment by sindresorhus** [comment]
Is `camelCase` really the best default? Most filesystems are case-insensitive. I would think `kebabCase` would be better.

**Comment by jamestalmage** [comment]
idea :+1: 

`camel-case` as default. :+1:

**Comment by sindresorhus** [comment]
> camel-case as default. :+1:

Why?

**Comment by jamestalmage** [comment]
I meant kebab

**Comment by jfmengels** [comment]
Huh. I usually write files in camel-case. Makes it easier to just copy-paste the filename :D `const fooBar = require('./fooBar');`.
I'm often scared when I propose a rule to you guys, that it will land in XO with a default value I don't like :p

**Comment by jamestalmage** [comment]
You are coordinating two different systems: The possibly case insensitive file system, and the language spec for identifiers.

Dashed names are much more readable, almost as good as a space. ThereIsAReasonWeDoNotWriteLikeThisOutsideOfProgrammingLanguages.

**Comment by jfmengels** [comment]
Ah yeah, forgot about OSX's case insensitivity... Ok, that makes good sense. I'll try to make a PR tomorrow.

**Comment by jfmengels** [comment]
Or now.
